"""Create a baseline migrations

Revision ID: ba3045d4f13e
Revises: 
Create Date: 2025-05-14 17:00:14.034938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba3045d4f13e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=False),
    sa.Column('inbox_uuid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inbox_uuid'], ['inbox.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_table('message')
    op.drop_table('inbox')
    # ### end Alembic commands ###
